# Operators
print(2 + 3)  
print(3 - 1)  
print(2 * 3)  
print(3 / 2)   
print(3 ** 2)   
print(3 % 2)   
print(3 // 2) 

# Checking data types
print(type(10))       
print(type(3.14))      
print(type(1 + 1j))      
print(type('You been pwnd'))  
print(type(True)) 
print(type(False))  
print(type([1, 2,3,4]))   
print(type({'name':'Dr.Fan', 'age':35, 'is_married': False})) 
print(type({1,2})) 
print(type(zip([1,2,3],[3,4]))) 
